// packages/react/src/App.tsx
import * as nacl from "tweetnacl";

import "./App.css";
import reactLogo from "./assets/react.svg";
import { KeysGenerator } from "./components/KeysGenerator";
import viteLogo from "/vite.svg";


function App({
  generateKey,
}: {
  generateKey: (secret: string) => nacl.BoxKeyPair;
}) {
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <KeysGenerator msg="Vite + React" generateKey={generateKey} />
      </div>
    </>
  );
}

export default App;

// packages/vue/src/App.vue
<script setup lang="ts">
import * as nacl from 'tweetnacl';
import HelloWorld from './components/HelloWorld.vue'

const { generateKey } = defineProps<{ generateKey: (secret: string) => nacl.BoxKeyPair }>()
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" :generate-key="generateKey" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
